/**
 * API Routes
 * Public API endpoints
 */

import { Router } from 'express';
import pool from '../../db/pool';

const router = Router();

// Basic health check endpoint
router.get('/health', (_req, res) => {
  res.json({
    status: 'ok',
    uptime: process.uptime(),
    timestamp: new Date().toISOString(),
  });
});

// Support server invite link
router.get('/support-invite', async (_req, res) => {
  try {
    // Get invite link from database (auto-generated by bot on startup)
    const result = await pool.query(
      'SELECT value FROM settings WHERE key = $1',
      ['support_server_invite']
    );

    if (result.rows.length === 0 || !result.rows[0].value) {
      return res.status(503).send('Support server invite not available yet. Please wait for bot to start and generate the invite link.');
    }

    const inviteLink = result.rows[0].value;
    res.redirect(inviteLink);
  } catch (error) {
    console.error('[API] Error fetching support invite:', error);
    res.status(500).send('Failed to fetch support server invite');
  }
});

export { router as apiRouter };
